# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Website & Mobile starter project

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform: AWS::Serverless-2016-10-31

# Shared configuration for all resources, more in
# https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    # The PermissionsBoundary allows users to safely develop with their function's permissions constrained
    # to their current application. All the functions and roles in this application have to include it and
    # it has to be manually updated when you add resources to your application.
    # More information in https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html
    PermissionsBoundary: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary"

Parameters:
  AppId:
    Type: String

  USER:
    Type: String
    Default: admin

  PASSWORD:
    Type: String
    Default: HS256

  HOST:
    Type: String
    Default: mutantes.cjel6cdq3euz.us-west-1.rds.amazonaws.com

  DB:
    Type: String
    Default: mutantes

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # Lambda Function Layer for Node.js
  LambdaFunctionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: mutants-dependencies
      Description: Dependencies for HealthEnviron Lambda Functions.
      ContentUri: src/dependencias/
      CompatibleRuntimes:
        - nodejs12.x
        - nodejs14.x
      LicenseInfo: MIT
      RetentionPolicy: Retain

  # This is a Lambda function config associated with the source code: get-all-items.js
  Mutant:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/mutantes
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 60
      Description: This Lambda Function allows to get mutants.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
      Layers:
        - !Ref LambdaFunctionLayer
      Environment:
        Variables:
          USER: !Ref USER
          PASSWORD: !Ref PASSWORD
          HOST: !Ref HOST
          DB: !Ref DB
      Events:
        Api:
          Type: Api
          Properties:
            Path: /mutant
            Method: POST

  Stats:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/stats
      Handler: index.statsHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 60
      Description: This Lambda Function allows to get stats mutants.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          USER: !Ref USER
          PASSWORD: !Ref PASSWORD
          HOST: !Ref HOST
          DB: !Ref DB
      Events:
        Api:
          Type: Api
          Properties:
            Path: /mutant
            Method: POST
